Merged Naor's mcpe1 branch code to the master one.
The goal here is to be able to load pre and post PE 1.0 worlds.

The pre 1.0 still works, and some progres has been made for the post 1.0

This code is implemented as the 'new feature' newPocketSupport.
**Itis highly recomended to use also the loadNBTCompoundList one.**

Notice that this code only implements loading functions, and not perfectly.
MCEdit will crash because of a bad index error when gathering chunk block data:

```
[   ERROR][                  root.py:1049]:MCEdit version Unified v1.5.6.0 %s Minecraft 1.8-1.11.2 | PE 0.11
Traceback (most recent call last):
  File "mcedit.py", line 1109, in <module>
    main(sys.argv)
  File "mcedit.py", line 1046, in main
    MCEdit.main()
  File "mcedit.py", line 890, in main
    rootwidget.run()
  File "<MCEdit-Unified path>/albow/root.py", line 168, in run
    self.run_modal(None)
  File "<MCEdit-Unified path>/albow/root.py", line 233, in run_modal
    self.gl_draw_all(self, (0, 0))
  File "<MCEdit-Unified path>/albow/widget.py", line 790, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "<MCEdit-Unified path>/albow/widget.py", line 790, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "<MCEdit-Unified path>/albow/widget.py", line 790, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "<MCEdit-Unified path>/albow/widget.py", line 790, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "<MCEdit-Unified path>/albow/widget.py", line 787, in gl_draw_all
    self.gl_draw_self(root, offset)
  File "<MCEdit-Unified path>/albow/openglwidgets.py", line 22, in gl_draw_self
    self.gl_draw_viewport()
  File "<MCEdit-Unified path>/albow/openglwidgets.py", line 28, in gl_draw_viewport
    self.gl_draw()
  File "<MCEdit-Unified path>/viewports/camera.py", line 1887, in gl_draw
    self.render()
  File "<MCEdit-Unified path>/viewports/chunk.py", line 83, in render
    super(ChunkViewport, self).render()
  File "<MCEdit-Unified path>/viewports/camera.py", line 1909, in render
    self.updateBlockFaceUnderCursor()
  File "<MCEdit-Unified path>/viewports/camera.py", line 350, in updateBlockFaceUnderCursor
    focusPair = self._findBlockFaceUnderCursor(mouse3dPoint)
  File "<MCEdit-Unified path>/viewports/camera.py", line 427, in _findBlockFaceUnderCursor
    neighborBlock = self.editor.level.blockAt(*point)
  File "<MCEdit-Unified path>/pymclevel/infiniteworld.py", line 483, in blockAt
    return ch.Blocks[xInChunk, zInChunk, y]
IndexError: index 16 is out of bounds for axis 2 with size 16
```